apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kanidm-operator-role-cluster
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [kanidm.github.io]
    resources: [accounts, groups, oauth2-clients, password-badlists, service-accounts, kanidms, users]
    verbs: [list, watch]
