apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ name | slugify }}-oauth2-credentials
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: kanidm
    app.kubernetes.io/instance: kanidm
    app.kubernetes.io/managed-by: kanidm-operator
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: kanidm
    app.kubernetes.io/created-by: kanidm-operator
    {% for key, value in extra_labels.items() %}
    {{ key }}: {{ value }}
    {% endfor %}
data:
  key: {{ client_id | b64enc }}
  secret: {{ secret | b64enc }}
