apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - group.yaml
  - kanidm.yaml
  - oauth2-client.yaml
  - user.yaml

namespace: kanidm-system

labels:
  - pairs:
      app.kubernetes.io/name: kanidm-operator
      app.kubernetes.io/instance: kanidm
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: kanidm-operator-crds
      app.kubernetes.io/part-of: kanidm
      app.kubernetes.io/version: 1.10.3-op.1
    includeSelectors: false
