name: Documentation

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry and dependencies
        run: |
          pip install poetry
          poetry env use 3.11
          poetry install --no-root --with docs

      - name: Build documentation
        run: poetry run mkdocs build --strict
